import { WidgetDef } from './types';

export const miniMapWidget: WidgetDef = {
  id: "mini-map",
  name: { tr: "Mini Harita", en: "Mini Map Radar", de: "Mini-Karten-Radar", es: "Mini Mapa Radar", fr: "Mini Carte Radar", pt: "Mini Mapa Radar", ru: "Мини-карта Радар" },
  description: { tr: "Canlı GPS takip radarı ve mini harita. Yayında anlık konumunuzu ve hızınızı şık bir harita üzerinde gösterir.", en: "Live GPS tracking radar and mini map.", de: "Live-GPS-Tracking-Radar und Minikarte.", es: "Radar GPS en vivo y mini mapa.", fr: "Radar GPS en direct et mini-carte.", pt: "Radar de rastreamento GPS e mini mapa.", ru: "Живой GPS-радар и мини-карта." },
  category: "IRL",
  fields: [
    { name: "channel", label: { tr: "Kanal / Cihaz Adı", en: "Kick Channel / Device ID", de: "Kanal / Geräte-ID", es: "Canal / ID", fr: "Chaîne / ID", pt: "Canal / ID", ru: "Канал / ID" }, type: "text", defaultValue: "itsfatih" },
    { name: "zoom", label: { tr: "Yakınlaştırma (Zoom)", en: "Zoom Level", de: "Zoom-Stufe", es: "Zoom", fr: "Zoom", pt: "Zoom", ru: "Масштаб" }, type: "select", defaultValue: "16", options: [{ label: { tr: "Yakın (Sokak - 17)", en: "Close (Street - 17)", de: "Nah", es: "Cerca", fr: "Près", pt: "Perto", ru: "Близко" }, value: "17" }, { label: { tr: "Standart (Mahalle - 15)", en: "Standard (Neighborhood - 15)", de: "Standard", es: "Estándar", fr: "Standard", pt: "Padrão", ru: "Стандарт" }, value: "15" }, { label: { tr: "Geniş (Şehir - 13)", en: "Wide (City - 13)", de: "Weit", es: "Amplio", fr: "Large", pt: "Amplo", ru: "Широко" }, value: "13" }] },
    { name: "mapTheme", label: { tr: "Harita Teması", en: "Map Style", de: "Kartenstil", es: "Tema", fr: "Style", pt: "Estilo", ru: "Стиль" }, type: "select", defaultValue: "dark", options: [{ label: { tr: "Karanlık Radar (Neon)", en: "Dark Radar (Cyberpunk)", de: "Dunkler Radar", es: "Radar Oscuro", fr: "Radar Sombre", pt: "Radar Escuro", ru: "Темный радар" }, value: "dark" }, { label: { tr: "Gece Modu (Midnight)", en: "Midnight Clean", de: "Mitternacht", es: "Modo Noche", fr: "Minuit", pt: "Meia-noite", ru: "Полночь" }, value: "midnight" }, { label: { tr: "Sokak Haritası", en: "Standard Street", de: "Standardkarte", es: "Mapa Estándar", fr: "Rue", pt: "Rua", ru: "Улицы" }, value: "light" }] },
    { name: "showSpeed", label: { tr: "Hız Göstergesi (km/s)", en: "Speedometer", de: "Geschwindigkeit", es: "Velocímetro", fr: "Compteur", pt: "Velocímetro", ru: "Спидометр" }, type: "select", defaultValue: "true", options: [{ label: { tr: "Açık", en: "Show", de: "Anzeigen", es: "Mostrar", fr: "Afficher", pt: "Mostrar", ru: "Показать" }, value: "true" }, { label: { tr: "Kapalı", en: "Hide", de: "Ausblenden", es: "Ocultar", fr: "Masquer", pt: "Ocultar", ru: "Скрыть" }, value: "false" }] },
    { name: "shape", label: { tr: "Harita Şekli", en: "Radar Shape", de: "Form", es: "Forma", fr: "Forme", pt: "Formato", ru: "Форма" }, type: "select", defaultValue: "circle", options: [{ label: { tr: "Yuvarlak Radar", en: "Round Radar (Circular)", de: "Kreis", es: "Circular", fr: "Circulaire", pt: "Circular", ru: "Круглый" }, value: "circle" }, { label: { tr: "Kavisli Kare (Kapsül)", en: "Rounded Square", de: "Quadrat", es: "Cuadrado", fr: "Carré", pt: "Quadrado", ru: "Квадрат" }, value: "square" }] }
  ]
};
